"""Build docs/DFHACK-INVENTORY.md from DFHack's own tool docs.

Inputs (all read-only copies taken from the install, kept out of the repo):
  --docs DIR        the install's hack/docs/docs/tools directory
  --tags FILE       the install's hack/docs/docs/Tags.txt
  --installed FILE  one relative script path per line, then a line
                    "==PLUGINS==", then one plugin name per line
  --out FILE        markdown to write

Every value comes from those files; nothing is taken from memory. A tool is
"installed" when a script or plugin file of that name exists, "doc only"
otherwise. "unavailable" is DFHack's own tag, not our judgement.
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MENTION_DIRS = ("research", "memory", "docs", "scripts/dfhack")
OURS_PREFIX = "df-overseer"


def parse_tool_doc(path: Path, root: Path) -> dict:
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    rel = path.relative_to(root).with_suffix("").as_posix()
    title = lines[0].strip() if lines else rel
    tags: list[str] = []
    commands: list[str] = []
    summary = ""
    for i, line in enumerate(lines[:40]):
        if line.startswith("Tags:"):
            tags = [t.strip() for t in line[5:].split("|") if t.strip()]
        elif re.match(r"Commands?:", line):
            commands = re.findall(r'"([^"]+)"', line)
        elif not summary and line.startswith("  ") and line.strip() and i > 2:
            summary = line.strip()
    return {"id": rel, "title": title, "tags": tags, "commands": commands, "summary": summary}


def load_installed(path: Path) -> tuple[set[str], set[str]]:
    scripts, plugins, in_plugins = set(), set(), False
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line:
            continue
        if line == "==PLUGINS==":
            in_plugins = True
        elif in_plugins:
            plugins.add(line)
        else:
            scripts.add(re.sub(r"\.(lua|rb)$", "", line))
    return scripts, plugins


def load_tag_groups(path: Path) -> dict[str, str]:
    groups, group = {}, ""
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        m = re.match(r'"?(\w+)"? tags$', line.strip())
        if m:
            group = m.group(1)
        m = re.match(r"\* (\w+):", line)
        if m:
            groups[m.group(1)] = group or "misc"
    return groups


def mentions(name: str, files: list[str]) -> int:
    pat = re.compile(r"(?<![\w-])" + re.escape(name) + r"(?![\w-])")
    return sum(1 for f in files if pat.search(f))


def build(docs: Path, tags_file: Path, installed_file: Path) -> tuple[list[dict], set[str], set[str]]:
    scripts, plugins = load_installed(installed_file)
    tools = [parse_tool_doc(p, docs) for p in sorted(docs.rglob("*.txt"))]
    for t in tools:
        base = t["id"]
        if base in scripts:
            t["kind"] = "script"
        elif base in plugins or any(c in plugins for c in t["commands"]):
            t["kind"] = "plugin"
        else:
            t["kind"] = "doc only"
        t["available"] = "unavailable" not in t["tags"]
    return tools, scripts, plugins


def render(tools: list[dict], scripts: set[str], plugins: set[str], groups: dict[str, str], files: list[str]) -> str:
    documented = {t["id"] for t in tools}
    undocumented = sorted(s for s in scripts if s not in documented and not s.startswith(("internal/", "devel/")) and not s.startswith(OURS_PREFIX))
    ours = sorted(s for s in scripts if s.startswith(OURS_PREFIX))
    tag_counts = Counter(tag for t in tools for tag in t["tags"])
    avail = [t for t in tools if t["available"]]
    out = []
    w = out.append
    w("# DFHack tool inventory (this install)\n")
    w("Generated by `scripts/dfhack_inventory.py` from DFHack's own tool docs and the")
    w("install's file listing, read-only, on 2026-09-21. **Regenerate rather than edit.**")
    w("DFHack version per `memory/dfhack-environment.md` (53.16-r1.1), not re-checked here.\n")
    w("## What this is, and is not\n")
    w("- **Names, tags and one-line summaries are DFHack's own words.** Nothing here was")
    w("  run. \"Available\" means DFHack does not tag it `unavailable`; it does not mean we")
    w("  have used it or that it works headless.")
    w("- **\"Mentions\" counts files** under `research/`, `memory/`, `docs/` and")
    w("  `scripts/dfhack/` that contain the tool's name as a whole word. It is approximate:")
    w("  common-word names (`sort`, `probe`, `plant`) overcount, and `0` means we have")
    w("  never written the name down, not that it is useless.")
    w("- **Tags are DFHack's.** `armok` means \"god-like powers or access to information the")
    w("  game hides\", which is the closest thing DFHack has to a cheat marker. The project")
    w("  has no written rule about them yet (see `Working.md`).\n")
    w("## Counts\n")
    w(f"- Documented tools: **{len(tools)}** ({len(avail)} available, {len(tools) - len(avail)} tagged `unavailable`).")
    w(f"- Installed script files: {len(scripts)} (of which {len(ours)} are ours, `{OURS_PREFIX}-*`); plugin files: {len(plugins)}.")
    w(f"- Documented and installed as a script: {sum(1 for t in tools if t['kind']=='script')}; as a plugin: {sum(1 for t in tools if t['kind']=='plugin')}; doc only: {sum(1 for t in tools if t['kind']=='doc only')} (the available ones are DFHack built-in commands such as `enable`, `help` and `ls`, which have no file; the unavailable ones ship no file at all).")
    w(f"- Installed scripts with no tool doc (excluding `internal/`, `devel/` and ours): {len(undocumented)}.\n")
    w("## Tag counts (all documented tools)\n")
    w("| Group | Tag | Tools |\n|---|---|---|")
    for tag, n in sorted(tag_counts.items(), key=lambda kv: (groups.get(kv[0], "~"), -kv[1])):
        w(f"| {groups.get(tag, '?')} | {tag} | {n} |")
    w("\n## Available `armok` tools (cheat-like, by DFHack's own tag)\n")
    w("| Tool | Kind | Summary |\n|---|---|---|")
    for t in avail:
        if "armok" in t["tags"]:
            w(f"| {t['id']} | {t['kind']} | {t['summary'][:110]} |")
    w("\n## Full inventory\n")
    w("Sorted by tool id. Columns: kind, availability, tags, summary, repo mentions.\n")
    w("| Tool | Kind | Avail | Tags | Summary | Mentions |\n|---|---|---|---|---|---|")
    for t in tools:
        names = [t["id"].split("/")[-1]] if not t["commands"] else t["commands"]
        n = max(mentions(x, files) for x in names) if names else 0
        tg = ", ".join(x for x in t["tags"] if x != "unavailable")
        w(f"| {t['id']} | {t['kind']} | {'yes' if t['available'] else 'no'} | {tg} | {t['summary'][:120].replace('|', '/')} | {n} |")
    w("\n## Installed scripts with no tool doc\n")
    w(", ".join(f"`{s}`" for s in undocumented) or "none")
    w("\n## Our own scripts\n")
    w(", ".join(f"`{s}`" for s in ours) or "none")
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--docs", required=True, type=Path)
    ap.add_argument("--tags", required=True, type=Path)
    ap.add_argument("--installed", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    a = ap.parse_args(argv)
    tools, scripts, plugins = build(a.docs, a.tags, a.installed)
    files = repo_text_files()
    a.out.write_text(render(tools, scripts, plugins, load_tag_groups(a.tags), files), encoding="utf-8", newline="\n")
    print(f"wrote {a.out}: {len(tools)} tools")
    return 0


def repo_text_files() -> list[str]:
    out = []
    for d in MENTION_DIRS:
        for p in (REPO / d).rglob("*"):
            if p.is_file() and p.suffix in {".md", ".yaml", ".lua", ".py", ".txt"}:
                out.append(p.read_text(encoding="utf-8", errors="replace"))
    return out


if __name__ == "__main__":
    sys.exit(main())
